/**
 * Location Types
 */
export const FETCH_LOCATIONS_SUCCESS = 'FETCH_LOCATIONS_SUCCESS'
export const FETCH_LOCATIONS_FAIL = 'FETCH_LOCATIONS_FAIL'
export const REQUEST_LOCATIONS_DATA = 'REQUEST_LOCATIONS_DATA'

/**
 * Search Types
 */
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS'
export const SEARCH_FAIL = 'SEARCH_FAIL'
export const REQUEST_SEARCH_DATA = 'REQUEST_SEARCH_DATA'